# Generated by Django 4.1.3 on 2022-12-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_employee_alter_car_cartype_alter_car_image_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
    ]
