# Generated by Django 4.1.3 on 2022-12-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.PositiveSmallIntegerField(choices=[(1, 'CLUBS'), (2, 'DIAMONDS'), (3, 'HEARTS'), (4, 'SPADES')])),
                ('number', models.PositiveSmallIntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, 'J'), (12, 'Q'), (13, 'K'), (14, 'A')])),
                ('image', models.ImageField(blank=True, default='B-Red.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('coin', models.IntegerField(default='1000')),
                ('image', models.ImageField(blank=True, default='car.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_name', models.CharField(default='deck_player_name', max_length=100)),
                ('amount_of_cards', models.IntegerField(default=52)),
                ('user_profile', models.OneToOneField(default='user_1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cards.userprofile')),
            ],
        ),
    ]
